import { FAMILY, PLAN_28, RECIPES, TRAINING_LOADS, SOURCES } from './data.js';
import { isMinor, canUseAdultBmi, bmi, adultBmiLabel, energyRange, proteinRange, hydrationTarget, portionProfile, contextualGuidance } from './nutrition-engine.js';
import { get, put, all, exportBackup, importBackup } from './storage.js';

const slots=['breakfast','lunch','snack','dinner'];
const slotLabel={breakfast:'Πρωινό',lunch:'Μεσημεριανό',snack:'Σνακ',dinner:'Βραδινό'};
const nav=[['today','Σήμερα'],['plan','Πλάνο'],['meals','Γεύματα'],['progress','Πρόοδος'],['family','Οικογένεια']];
const allowedViews=new Set(nav.map(x=>x[0]));
const allowedLoads=new Set(TRAINING_LOADS.map(x=>x[0]));
let state={view:'today',member:'mother',theme:'dark',trainingLoad:'normal',profiles:structuredClone(FAMILY),today:{}};

const el=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const recipe=id=>RECIPES.find(r=>r.id===id);
const profile=()=>state.profiles.find(p=>p.id===state.member)||state.profiles[0];
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
function mondayIndex(d=new Date()){const start=new Date(d.getFullYear(),0,1);const startDow=(start.getDay()+6)%7;const days=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-start)/86400000);return ((days+startDow)%28)+1;}
function planForToday(){return PLAN_28[mondayIndex()-1];}
function toast(msg){const t=el('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2600);}
function currentTrainingLoad(p){return p.athlete?state.trainingLoad:'normal';}
function normalizeState(){if(!allowedViews.has(state.view))state.view='today';if(!allowedLoads.has(state.trainingLoad))state.trainingLoad='normal';if(!state.profiles.some(p=>p.id===state.member))state.member=state.profiles[0]?.id||'mother';}

async function load(){
  try{
    const settings=await get('settings','app');
    if(settings) state={...state,...settings};
    const profiles=await all('profiles'); if(profiles.length)state.profiles=profiles;
    const requested=new URLSearchParams(location.search).get('view'); if(allowedViews.has(requested))state.view=requested;
    normalizeState();
    document.documentElement.dataset.theme=state.theme;
    document.documentElement.style.setProperty('--accent',profile().accent||'#55d6a7');
    const log=await get('logs',`${localDateKey()}:${state.member}`);if(log)state.today[state.member]=log;
    renderShell();await render();
  }catch(error){console.error(error);el('view').innerHTML='<section class="notice">Δεν ήταν δυνατή η φόρτωση των τοπικών δεδομένων. Δοκίμασε επαναφόρτωση ή private backup restore.</section>';toast('Σφάλμα τοπικής αποθήκευσης');}
}
async function persist(){await put('settings',{id:'app',view:state.view,member:state.member,theme:state.theme,trainingLoad:state.trainingLoad});for(const p of state.profiles)await put('profiles',p);}

function renderShell(){
  const html=nav.map(([id,label])=>`<button data-view="${id}" class="${state.view===id?'active':''}">${label}</button>`).join('');el('sideNav').innerHTML=html;el('mobileNav').innerHTML=html;
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=async()=>{state.view=b.dataset.view;history.replaceState(null,'',`${location.pathname}?view=${state.view}`);await persist();renderShell();await render();});
  el('memberSwitch').innerHTML=state.profiles.map(p=>`<button class="chip ${p.id===state.member?'active':''}" data-member="${esc(p.id)}">${esc(p.name)}</button>`).join('');
  document.querySelectorAll('[data-member]').forEach(b=>b.onclick=async()=>{state.member=b.dataset.member;document.documentElement.style.setProperty('--accent',profile().accent||'#55d6a7');const log=await get('logs',`${localDateKey()}:${state.member}`);state.today[state.member]=log||{};await persist();renderShell();await render();});
  el('themeBtn').textContent=state.theme==='dark'?'Light':'Dark';el('themeBtn').onclick=async()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;el('themeBtn').textContent=state.theme==='dark'?'Light':'Dark';await persist();};
}

function todayPlanHtml(){const day=planForToday(),log=state.today[profile().id]||{};return `<div class="meal-grid">${slots.map(s=>{const r=recipe(day[s]);const done=log[s]?.status==='done';return `<article class="meal"><div class="slot">${slotLabel[s]}</div><h3>${esc(r.name)}</h3><div class="muted">${r.time}′ · ~${r.base.kcal} kcal base recipe</div><div class="meal-actions"><button class="chip ${done&&log[s]?.portion===.75?'active':''}" data-meal="${s}" data-portion="0.75">Μικρότερη</button><button class="chip ${done&&log[s]?.portion===1?'active':''}" data-meal="${s}" data-portion="1">${done&&log[s]?.portion===1?'✓ Έγινε':'Όπως το πλάνο'}</button><button class="chip ${done&&log[s]?.portion===1.25?'active':''}" data-meal="${s}" data-portion="1.25">Μεγαλύτερη</button></div></article>`}).join('')}</div>`;}

function todayView(){
  const p=profile(),load=currentTrainingLoad(p),day=planForToday(),portions=portionProfile(p,load),er=energyRange(p,load),pr=proteinRange(p),hyd=hydrationTarget(p,load),log=state.today[p.id]||{};
  const nextSlot=slots.find(s=>log[s]?.status!=='done')||'dinner',next=recipe(day[nextSlot]),guidance=contextualGuidance({profile:p,trainingLoad:load,today:log,plannedMeal:next});
  return `<section class="hero"><div class="eyebrow">${esc(p.role)}</div><h1>${esc(p.name)}: τι χρειάζεται τώρα</h1><p>Action-first καθημερινό πλάνο με διαφορετικούς κανόνες για ενήλικες, εφήβους και αθλητές.</p></section><section class="card next"><div class="eyebrow">NEXT</div><div class="name">${esc(next.name)}</div><p class="muted">${slotLabel[nextSlot]} · ${p.athlete?esc(TRAINING_LOADS.find(x=>x[0]===load)?.[1]||'Training'):'Οικογενειακό πλάνο'}</p></section>
  <div class="grid g3" style="margin-top:16px"><section class="card"><div class="muted">Energy planning estimate</div><div class="metric">${er.lower}–${er.upper}<small> kcal/day</small></div><p class="muted">${esc(er.note)}</p></section><section class="card"><div class="muted">Protein planning range</div><div class="metric">${pr.min}–${pr.max}<small> g/day</small></div><p class="muted">${esc(pr.note)}</p></section><section class="card"><div class="muted">Hydration starting estimate</div><div class="metric">${(hyd.ml/1000).toFixed(1)}<small> L/day</small></div><p class="muted">${esc(hyd.note)}</p></section></div>
  ${p.athlete?`<section class="card" style="margin-top:16px"><div class="eyebrow">ATHLETE MODE</div><h2>Training load</h2><div class="member-switch" style="margin-top:12px">${TRAINING_LOADS.map(([id,label])=>`<button class="chip ${id===load?'active':''}" data-load="${id}">${esc(label)}</button>`).join('')}</div><p class="muted">Training load changes carbohydrate portions and hydration estimates; it never creates a weight-loss target for this minor profile.</p></section>`:''}
  <section class="card" style="margin-top:16px"><h2>Σήμερα</h2><div class="timeline">${slots.map(s=>`<div class="step ${log[s]?.status==='done'?'done':s===nextSlot?'current':''}"><i class="dot"></i><div><b>${slotLabel[s]}</b><div class="muted">${esc(recipe(day[s]).name)}${log[s]?.portion?` · ${log[s].portion}×`:''}</div></div></div>`).join('')}</div></section><section style="margin-top:16px">${todayPlanHtml()}</section>
  <div class="grid g2" style="margin-top:16px"><section class="card"><h3>Portion profile · ${esc(portions.label)}</h3><div class="portion-row" style="margin-top:12px"><div class="portion"><b>${portions.vegetables}×</b><span class="muted">Vegetables</span></div><div class="portion"><b>${portions.protein}×</b><span class="muted">Protein</span></div><div class="portion"><b>${portions.carbs}×</b><span class="muted">Carbs</span></div><div class="portion"><b>${portions.fats}×</b><span class="muted">Fats</span></div></div></section><section class="card"><h3>Context, όχι αυθαίρετο score</h3>${guidance.map(t=>`<div class="status"><span>${esc(t)}</span><b class="good">✓</b></div>`).join('')}</section></div>`;
}

function planView(){const currentWeek=Math.ceil(mondayIndex()/7),days=PLAN_28.filter(d=>d.week===currentWeek);return `<section class="hero"><div class="eyebrow">28-DAY ROTATION</div><h1>Το πλάνο της εβδομάδας</h1><p>Ο κύκλος είναι ευθυγραμμισμένος με Δευτέρα–Κυριακή και προσαρμόζεται με member-specific portions.</p></section><div class="plan-week">${days.map(d=>`<section class="card day"><div class="eyebrow">W${d.week}</div><h3>${d.dow}</h3>${slots.map(s=>`<div class="tiny-meal"><span>${slotLabel[s]}</span>${esc(recipe(d[s]).name)}</div>`).join('')}</section>`).join('')}</div><section class="card" style="margin-top:16px"><h2>Batch-cook priority</h2><p class="muted">Μαγείρεψε 1 όσπριο, 1 tray-bake πρωτεΐνη, 1 cooked grain και πλύνε σαλάτες.</p><button class="btn" id="shoppingBtn">Λίστα αγορών εβδομάδας</button><div id="shoppingOut"></div></section>`;}
function mealsView(){return `<section class="hero"><div class="eyebrow">MEAL LIBRARY</div><h1>Λιγότερες, καλύτερες συνταγές</h1><p>Τα macros είναι estimates της βασικής συνταγής και δεν καταγράφονται ως κατανάλωση χωρίς επιβεβαίωση.</p></section><div class="recipe-list">${RECIPES.map(r=>`<article class="recipe"><div class="eyebrow">${slotLabel[r.slot]||esc(r.slot)}</div><h3>${esc(r.name)}</h3><p class="meta">${r.time}′ · ${r.base.kcal} kcal · P ${r.base.p}g · C ${r.base.c}g · F ${r.base.f}g</p><p class="muted">${r.ingredients.map(esc).join(' · ')}</p></article>`).join('')}</div>`;}

async function progressView(){const p=profile(),logs=(await all('logs')).filter(x=>x.memberId===p.id),measurements=(await all('measurements')).filter(x=>x.memberId===p.id).sort((a,b)=>a.date.localeCompare(b.date)),adultBmi=canUseAdultBmi(p),bmiValue=bmi(p),label=adultBmiLabel(p),last=measurements.at(-1);return `<section class="hero"><div class="eyebrow">PROGRESS</div><h1>Τάσεις, όχι ενοχές</h1><p>Διαφανείς καταγραφές χωρίς αυθαίρετο health score.</p></section><div class="grid g3"><section class="card"><div class="muted">Logged days</div><div class="metric">${logs.length}</div></section><section class="card"><div class="muted">Measurements</div><div class="metric">${measurements.length}</div></section><section class="card"><div class="muted">BMI</div><div class="metric">${adultBmi?bmiValue:'—'}<small>${adultBmi?` · ${esc(label)}`:' age-specific interpretation required'}</small></div></section></div>${!adultBmi?'<div class="notice" style="margin-top:16px">Για ηλικίες κάτω των 20 το ZENITH δεν εμφανίζει adult BMI κατηγορίες. Παιδιά/έφηβοι χρειάζονται age- and sex-specific αξιολόγηση.</div>':''}<section class="card" style="margin-top:16px"><h2>Καταγραφή βάρους</h2><form class="form measure-form" id="measurementForm"><div class="grid g2"><label>Ημερομηνία<input name="date" type="date" value="${localDateKey()}" required></label><label>Βάρος kg<input name="weight" type="number" min="20" max="300" step="0.1" value="${last?.weight??p.weight}" required></label></div><button class="btn" type="submit">Αποθήκευση μέτρησης</button></form>${last?`<p class="muted">Τελευταία καταγραφή: ${esc(last.date)} · ${last.weight} kg</p>`:''}</section>`;}

function familyView(){const p=profile();return `<section class="hero"><div class="eyebrow">FAMILY</div><h1>Προφίλ & ασφάλεια</h1><p>Οι ρυθμίσεις καθορίζουν ποια nutrition logic επιτρέπεται.</p></section><div class="grid g2"><section class="card"><form class="form" id="profileForm"><label>Όνομα<input name="name" maxlength="40" value="${esc(p.name)}" required></label><div class="grid g2"><label>Ηλικία<input name="age" type="number" min="2" max="110" value="${p.age}" required></label><label>Φύλο<select name="sex"><option value="f" ${p.sex==='f'?'selected':''}>Female</option><option value="m" ${p.sex==='m'?'selected':''}>Male</option></select></label><label>Ύψος cm<input name="height" type="number" min="80" max="230" value="${p.height}" required></label><label>Βάρος kg<input name="weight" type="number" min="20" max="300" step="0.1" value="${p.weight}" required></label></div><label>Goal<select name="goal" ${isMinor(p)?'disabled':''}><option value="maintain" ${p.goal==='maintain'?'selected':''}>Maintain</option><option value="gradual_fat_loss" ${p.goal==='gradual_fat_loss'?'selected':''}>Gradual fat loss (adults only)</option><option value="growth" ${p.goal==='growth'?'selected':''}>Growth</option><option value="performance" ${p.goal==='performance'?'selected':''}>Performance</option></select></label><button class="btn" type="submit">Αποθήκευση</button></form></section><section class="card"><h3>Privacy & backup</h3><p class="muted">Τα δεδομένα μένουν στη συσκευή σε IndexedDB. Το JSON export είναι portable backup· το restore γίνεται atomically.</p><div class="meal-actions"><button class="btn" id="exportBtn">Export JSON</button><button class="btn" id="importBtn">Import JSON</button></div><h3 style="margin-top:20px">Evidence links</h3><div class="source-list">${SOURCES.map(s=>`<p><a href="${s.url}" target="_blank" rel="noopener noreferrer">${esc(s.label)}</a></p>`).join('')}</div></section></div>`;}

async function render(){const view=el('view');if(state.view==='today')view.innerHTML=todayView();else if(state.view==='plan')view.innerHTML=planView();else if(state.view==='meals')view.innerHTML=mealsView();else if(state.view==='progress')view.innerHTML=await progressView();else view.innerHTML=familyView();bind();}
function bind(){
  document.querySelectorAll('[data-load]').forEach(b=>b.onclick=async()=>{if(!profile().athlete)return;state.trainingLoad=b.dataset.load;await persist();await render();});
  document.querySelectorAll('[data-meal]').forEach(b=>b.onclick=async()=>{const p=profile(),date=localDateKey();state.today[p.id]??={};state.today[p.id][b.dataset.meal]={status:'done',portion:Number(b.dataset.portion)};await put('logs',{id:`${date}:${p.id}`,date,memberId:p.id,...state.today[p.id]});await render();toast('Γεύμα καταγράφηκε.');});
  el('shoppingBtn')?.addEventListener('click',()=>{const week=PLAN_28.filter(d=>d.week===Math.ceil(mondayIndex()/7)),counts=new Map();for(const d of week)for(const s of slots)for(const item of recipe(d[s]).ingredients)counts.set(item,(counts.get(item)||0)+1);el('shoppingOut').innerHTML=`<div class="recipe-list" style="margin-top:12px">${[...counts.entries()].sort((a,b)=>a[0].localeCompare(b[0],'el')).map(([x,n])=>`<div class="recipe"><b>${esc(x)}</b><div class="muted">Χρησιμοποιείται σε ${n} γεύμα${n===1?'':'τα'} της εβδομάδας</div></div>`).join('')}</div>`;});
  el('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),p=profile(),age=Number(fd.get('age')),height=Number(fd.get('height')),weight=Number(fd.get('weight'));if(!Number.isFinite(age)||!Number.isFinite(height)||!Number.isFinite(weight))return toast('Έλεγξε τα αριθμητικά πεδία.');p.name=String(fd.get('name')||'').trim().slice(0,40)||p.name;p.age=age;p.sex=fd.get('sex');p.height=height;p.weight=weight;if(!isMinor(p))p.goal=fd.get('goal');else p.goal=p.athlete?'performance':'growth';await persist();renderShell();await render();toast('Το προφίλ ενημερώθηκε.');});
  el('measurementForm')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target),p=profile(),date=fd.get('date'),weight=Number(fd.get('weight'));if(!date||!Number.isFinite(weight)||weight<20||weight>300)return toast('Μη έγκυρη μέτρηση.');await put('measurements',{id:`${p.id}:${date}`,memberId:p.id,date,weight});p.weight=weight;await persist();await render();toast('Η μέτρηση αποθηκεύτηκε.');});
  el('exportBtn')?.addEventListener('click',async()=>{const data=await exportBackup(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`zenith-backup-${localDateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  el('importBtn')?.addEventListener('click',()=>el('backupImport').click());
}

el('backupImport').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{await importBackup(JSON.parse(await file.text()));toast('Backup restored. Reloading…');setTimeout(()=>location.reload(),700);}catch(err){console.error(err);toast('Μη έγκυρο backup — δεν έγινε καμία αλλαγή.');}finally{e.target.value='';}});

if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{reg.update().catch(()=>{});reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('Νέα έκδοση εγκαταστάθηκε — ανανέωσε την εφαρμογή.');});});}).catch(console.error);}
load();
